frequency: 20
delay: 0.0
magnetic_declination_radians: 0
yaw_offset: 0.0
zero_altitude: false
broadcast_utm_transform: false
broadcast_utm_transform_as_parent_frame: false
publish_filtered_gps: true 
